services:
  backend:
    build: ./backend
    expose:
      - "8081"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health/"]
      interval: 10s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 3
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M
          cpus: "0.5"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: &frontend_vars
        NODE_ENV: ${NODE_ENV:-production}
        VUE_APP_API_URL: ${VUE_APP_API_URL:-/api}
        APP_PATH: ${APP_PATH:-/momo-store}
    ports:
      - "80:80"
    environment: *frontend_vars
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
          cpus: "0.25"
    volumes:
      - nginx_logs:/var/log/nginx
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

volumes:
  nginx_logs:

networks:
  app-network:
    driver: bridge
